name: Run scraper

on:
  schedule:
     - cron: "7 20 */5 * *"
  push:
permissions:
  contents: write

jobs:
  scrape:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run scraper
      env:
        NSSCTF_USERNAME: ${{ secrets.NSSCTF_USERNAME }}
        NSSCTF_PASSWORD: ${{ secrets.NSSCTF_PASSWORD }}
      run: | 
        python main.py
    - name: Copy infos
      run: | 
        diff infos.json public/infos.json ||
        cp infos.json public/ &&
        git config --local user.email "actions@github.com" &&
        git config --local user.name "GitHub Actions" &&
        git add . && git commit -m 'Update: '"$(date)" && git push
